AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/distributions/java-lambda.zip
      Handler: example.Handler
      Runtime: java8
      Description: Java function
      MemorySize: 512
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
      Environment:
        Variables:
          NEW_RELIC_ACCOUNT_ID: XXXX
          NEW_RELIC_PRIMARY_APPLICATION_ID: XXXX
          NEW_RELIC_TRUSTED_ACCOUNT_KEY: XXXX
          NEW_RELIC_DEBUG: false

